/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class EditStudent extends javax.swing.JFrame {

    /**
     * Creates new form EditStudent
     */
    public EditStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        fathername = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        rollno = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        fatherphone = new javax.swing.JTextField();
        classAttend = new javax.swing.JTextField();
        UpdateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(305, 100, 0, 0));
        setMinimumSize(new java.awt.Dimension(670, 590));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Students' Records");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 480, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Father Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Phone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Father Phone:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Class:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Roll Number:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 100, -1));

        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 270, 40));

        fathername.setBackground(new java.awt.Color(51, 51, 51));
        fathername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fathername.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fathername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 270, 40));

        phone.setBackground(new java.awt.Color(51, 51, 51));
        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 270, 40));

        rollno.setBackground(new java.awt.Color(51, 51, 51));
        rollno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rollno.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 270, 40));

        id.setBackground(new java.awt.Color(51, 51, 51));
        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 270, 40));

        address.setBackground(new java.awt.Color(51, 51, 51));
        address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        address.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 270, 40));

        fatherphone.setBackground(new java.awt.Color(51, 51, 51));
        fatherphone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fatherphone.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fatherphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 270, 40));

        classAttend.setBackground(new java.awt.Color(51, 51, 51));
        classAttend.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classAttend.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(classAttend, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 270, 40));

        UpdateBtn.setBackground(new java.awt.Color(51, 51, 51));
        UpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(204, 204, 204));
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, -1, 30));

        backBtn.setBackground(new java.awt.Color(51, 51, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        backBtn.setForeground(new java.awt.Color(204, 204, 204));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
     
            String idString = id.getText();
            String sname = name.getText();
            String fname = fathername.getText();
            String ph = phone.getText();
            String fph = fatherphone.getText();
            String cla = classAttend.getText();
            String rollNO = rollno.getText();
            String saddress = address.getText();
            
            if (idString.isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields must be filled!");
            } else if (sname.isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields must be filled!");
            } else if (ph.isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields must be filled!");
            } else if (cla.isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields must be filled!");
            } else if (rollNO.isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields must be filled!");
            } else if (saddress.isEmpty()) {
                JOptionPane.showMessageDialog(null, "All fields must be filled!");
            } else {
            
                
            String sidRegex =  "^\\d{1,10}$";
            String nameRegex = "^[A-Za-z]+([-'][A-Za-z]+)*$";
            String phoneRegex = "^09\\d{7,9}$";
            String classRegex = "^[A-Za-z0-9 ]+$";
            String rollNumRegex = "^[A-Za-z0-9]+$";
            String addressRegex = "^[A-Za-z0-9.,#\\-/ ]+$";

            
            if(idString.matches(sidRegex) && sname.matches(nameRegex) && fname.matches(nameRegex) && ph.matches(phoneRegex) && fph.matches(phoneRegex) && cla.matches(classRegex) && rollNO.matches(rollNumRegex) && saddress.matches(addressRegex)){
                          int sid = Integer.parseInt(idString);

                   try{
                                   

                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");

                        // Search.....
                        Statement statement = connection.createStatement();

                        String query = "SELECT * FROM studentregistrationinfo Where id = " + sid + " AND name = '" + sname + "'";
                        ResultSet resultSet = statement.executeQuery(query);

                        if(resultSet.next()){

                            String sql = "UPDATE studentregistrationinfo SET father_name = ?, phone = ?, father_phone = ?, class = ?, roll = ?, address = ? WHERE id = ? AND name = ?";

                            PreparedStatement pstmt = connection.prepareStatement(sql);

                            pstmt.setString(1, fname);
                            pstmt.setString(2, ph);
                            pstmt.setString(3, fph);
                            pstmt.setString(4, cla);
                            pstmt.setString(5, rollNO);
                            pstmt.setString(6, saddress);
                            pstmt.setInt(7, sid); // Assuming `id` is an integer
                            pstmt.setString(8, sname);

                            pstmt.execute();
                            connection.close();

                            id.setText("");
                            name.setText("");
                            phone.setText("");
                            fatherphone.setText("");
                            fathername.setText("");
                            classAttend.setText("");
                            rollno.setText("");
                            address.setText("");

                            JOptionPane.showMessageDialog(null, "Record has been updated successfully");

                        } else{

                           JOptionPane.showMessageDialog(null, "Data not found");

                           id.setText("");
                           name.setText("");
                           phone.setText("");
                           fatherphone.setText("");
                           fathername.setText("");
                           classAttend.setText("");
                           rollno.setText("");
                           address.setText("");
                        }          

                        }catch(Exception e){
                            JOptionPane.showMessageDialog(null, e);
                        }
            }else{
                JOptionPane.showMessageDialog(null, "Try Again. Insert appropriate values to the fields!");
            }
            
            }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        StudentModule studentModule = new StudentModule();
        studentModule.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTextField address;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField classAttend;
    private javax.swing.JTextField fathername;
    private javax.swing.JTextField fatherphone;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField rollno;
    // End of variables declaration//GEN-END:variables
}
