/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package schoolmanagementsystem;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UsernameButton = new javax.swing.JTextField();
        PasswordButton = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sc = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        scButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(300, 140, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("LOGIN PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("SCHOOL MANAGEMENT SYSTEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 131, 387, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 294, 110, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Username:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 225, 110, 36));

        UsernameButton.setBackground(new java.awt.Color(51, 51, 51));
        UsernameButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        UsernameButton.setForeground(new java.awt.Color(204, 204, 204));
        UsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 226, 239, 36));

        PasswordButton.setBackground(new java.awt.Color(51, 51, 51));
        PasswordButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PasswordButton.setForeground(new java.awt.Color(204, 204, 204));
        PasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 288, 237, 34));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Forgot Password?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Enter secret code: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 424, 170, -1));

        sc.setBackground(new java.awt.Color(51, 51, 51));
        sc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        sc.setForeground(new java.awt.Color(204, 204, 204));
        sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scActionPerformed(evt);
            }
        });
        getContentPane().add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 420, 161, 31));

        loginButton.setBackground(new java.awt.Color(51, 51, 51));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        loginButton.setForeground(new java.awt.Color(204, 204, 204));
        loginButton.setText("Submit");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 110, 32));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystem/ppppp.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 0, 159, -1));

        scButton.setBackground(new java.awt.Color(51, 51, 51));
        scButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        scButton.setForeground(new java.awt.Color(204, 204, 204));
        scButton.setText("Request");
        scButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scButtonActionPerformed(evt);
            }
        });
        getContentPane().add(scButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 90, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameButtonActionPerformed

    private void scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scActionPerformed

    private void PasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
             String userName = UsernameButton.getText();
             String password = PasswordButton.getText();
             
             if(userName.isEmpty() || password.isEmpty()){
                   JOptionPane.showMessageDialog(null, "All fields must be filled!");

             }else{
                 
                    if(userName.matches("^[A-Za-z]+([-'][A-Za-z]+)*$") && password.matches("^[A-Za-z0-9!@#$%^&*()_+=\\-{}\\[\\]:;\"'<>,.?/~`|\\\\]{4,}$")){
                
                        try {
                           Class.forName("com.mysql.cj.jdbc.Driver");

                           Connection connection = DriverManager.getConnection(  "jdbc:mysql://localhost:3306/sms", "root", "");
                           Statement statement = connection.createStatement();

                           String query = "SELECT * FROM user_login";
                           ResultSet resultSet = statement.executeQuery(query);


                                while (resultSet.next()) {
                                    String userNameDb = resultSet.getString("username");
                                    String passwordDb = resultSet.getString("password");

                                    if (userName.equals(userNameDb) && password.equals(passwordDb)) {
                                      new Menu().setVisible(true);
                                      dispose();
                                    }else{
                                        JOptionPane.showMessageDialog(null, "incorrect username or password");
                                    }
                                }

                       } catch (ClassNotFoundException e) {
                           JOptionPane.showMessageDialog(this, "MySQL Driver not found: " + e.getMessage());

                       } catch (SQLException e) {
                           JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());

                       } catch (Exception e) {
                           JOptionPane.showMessageDialog(this, "Unexpected error: " + e.getMessage());

                       }
            }else{
                     JOptionPane.showMessageDialog(null, "UserName should be only letters and A Password should have at least four characters!");

                 }
       }


    }//GEN-LAST:event_loginButtonActionPerformed

    
    private void scButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scButtonActionPerformed
        String secret = sc.getText();
        
        if(secret.equals("admin@123")){
            JOptionPane.showMessageDialog(this, "The username and password is admin");
            sc.setText("");  
        }
        
    }//GEN-LAST:event_scButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordButton;
    private javax.swing.JTextField UsernameButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField sc;
    private javax.swing.JButton scButton;
    // End of variables declaration//GEN-END:variables
}
