/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;

import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class SandDStudent extends javax.swing.JFrame {

    /**
     * Creates new form SandDStudent
     */
    public SandDStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        retrieveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idTextToSearch = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(260, 110, 0, 0));
        setMinimumSize(new java.awt.Dimension(780, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search & Delete Students");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 33, 450, -1));

        stuTable.setBackground(new java.awt.Color(204, 204, 204));
        stuTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stuTable.setForeground(new java.awt.Color(51, 51, 51));
        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "   id", "    name", "    father_name", "   phone", "   father_phone", "    class", "    roll_no", "   address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        stuTable.setAutoscrolls(false);
        stuTable.setFocusable(false);
        stuTable.setRowHeight(25);
        stuTable.setRowMargin(3);
        stuTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        stuTable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        stuTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                stuTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(stuTable);
        if (stuTable.getColumnModel().getColumnCount() > 0) {
            stuTable.getColumnModel().getColumn(0).setPreferredWidth(25);
            stuTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            stuTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            stuTable.getColumnModel().getColumn(3).setPreferredWidth(120);
            stuTable.getColumnModel().getColumn(4).setPreferredWidth(120);
            stuTable.getColumnModel().getColumn(5).setPreferredWidth(70);
            stuTable.getColumnModel().getColumn(6).setPreferredWidth(55);
            stuTable.getColumnModel().getColumn(7).setMinWidth(25);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 880, 140));

        retrieveBtn.setBackground(new java.awt.Color(51, 51, 51));
        retrieveBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        retrieveBtn.setForeground(new java.awt.Color(204, 204, 204));
        retrieveBtn.setText("Retrieve Records");
        retrieveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(retrieveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 240, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Insert the id to delete specific student:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        idText.setBackground(new java.awt.Color(51, 51, 51));
        idText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idText.setForeground(new java.awt.Color(204, 204, 204));
        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        getContentPane().add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 90, -1));

        deleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(204, 204, 204));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 110, -1));

        backBtn.setBackground(new java.awt.Color(51, 51, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(204, 204, 204));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Insert the id to search specific student:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        idTextToSearch.setBackground(new java.awt.Color(51, 51, 51));
        idTextToSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idTextToSearch.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(idTextToSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 90, -1));

        Search.setBackground(new java.awt.Color(51, 51, 51));
        Search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Search.setForeground(new java.awt.Color(204, 204, 204));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 110, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        StudentModule stmodule = new StudentModule();
        stmodule.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void retrieveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveBtnActionPerformed
         
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");
            
            String query = "select * from studentregistrationinfo";
            
            Statement statement = connection.createStatement();
            ResultSet rs = statement.executeQuery(query);
            
            DefaultTableModel tm = (DefaultTableModel)stuTable.getModel();
            tm.setRowCount(0);
            
            while(rs.next()){
                Object obj[] =
                {rs.getInt("id"),rs.getString("name"),rs.getString("father_name"), rs.getString("phone"), rs.getString("father_phone"),rs.getString("class"), rs.getString("roll"), rs.getString("address")};
            
                tm.addRow(obj);
            }
            
            connection.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_retrieveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        
        String id = idText.getText();
          if(!id.isEmpty()){
              
        
        if(id.matches("^\\d{1,10}$")){
            int sid = Integer.parseInt(id);
            try{
                
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");

                   // Search.....
                    Statement statement = connection.createStatement();

                    String query = "select * from studentregistrationinfo Where id = " + sid;
                    ResultSet resultSet = statement.executeQuery(query);

                    if(resultSet.next()){

                        String deleteQuery = "delete from studentregistrationinfo where id = ? " ;
                        PreparedStatement pst = connection.prepareStatement(deleteQuery);
                        pst.setInt(1, sid); 
                        pst.executeUpdate();

                        idText.setText("");

                        JOptionPane.showMessageDialog(null, "Deleted Successfully");
                        connection.close();

                    } else{

                       JOptionPane.showMessageDialog(null, "Data not found ");

                    }          
                    
            }catch(Exception e){
                JOptionPane.showMessageDialog(null , e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please enter the appropriate ID"); 
        }
    
              
          }else{
              JOptionPane.showMessageDialog(null, "ID field cannot be empty!");

          }
    
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
        String id = idTextToSearch.getText();
        
        if(!id.isEmpty()){
            
                 if(id.matches("^\\d{1,10}$")){
            
                 try{
            
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");

                        String query1 = "select * from studentregistrationinfo where id = ? ";

                        PreparedStatement pst1 = connection.prepareStatement(query1);
                        pst1.setInt(1, Integer.parseInt(id));
                        ResultSet rs1 = pst1.executeQuery();

                        if(rs1.next()){

                            String query2 = "select * from studentregistrationinfo where id = ? ";
                            PreparedStatement pst2 = connection.prepareStatement(query2);
                            pst2.setInt(1, Integer.parseInt(id));
                            ResultSet rs2 =pst2.executeQuery(); 

                            DefaultTableModel tm = (DefaultTableModel)stuTable.getModel();
                            tm.setRowCount(0);

                            while(rs2.next()){

                                Object obj[] =
                                  {rs2.getInt("id"),rs2.getString("name"),rs2.getString("father_name"), rs2.getString("phone"), rs2.getString("father_phone"),rs2.getString("class"), rs2.getString("roll"), rs2.getString("address")};

                                tm.addRow(obj);

                             }

                              connection.close();
                              idTextToSearch.setText("");

                        }else{
                            JOptionPane.showMessageDialog(null, "Data not found");
                            idTextToSearch.setText("");

                        }
               
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }

        }else{
             JOptionPane.showMessageDialog(null, "Please enter the appropriate ID"); 
        }
        
            
        }else{
            JOptionPane.showMessageDialog(null, "ID field cannot be empty!");

        }
            
   
    }//GEN-LAST:event_SearchActionPerformed

    private void stuTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_stuTablePropertyChange
        stuTable.getTableHeader().setFont(new java.awt.Font("Arial", Font.PLAIN, 18
        )); // Set your preferred font and size

    }//GEN-LAST:event_stuTablePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SandDStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SandDStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SandDStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SandDStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SandDStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField idTextToSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retrieveBtn;
    private javax.swing.JTable stuTable;
    // End of variables declaration//GEN-END:variables
}
