/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;

/**
 *
 * @author ASUS
 */
public class StudentModule extends javax.swing.JFrame {

    /**
     * Creates new form StudentModule
     */
    public StudentModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchDeleteBtn = new javax.swing.JButton();
        addStudentBtn = new javax.swing.JButton();
        editStudentBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 140, 0, 0));
        setMinimumSize(new java.awt.Dimension(620, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 29)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT MODULE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 340, 50));

        searchDeleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        searchDeleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        searchDeleteBtn.setForeground(new java.awt.Color(204, 204, 204));
        searchDeleteBtn.setText("Search & Delete Student");
        searchDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 280, 50));

        addStudentBtn.setBackground(new java.awt.Color(51, 51, 51));
        addStudentBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        addStudentBtn.setForeground(new java.awt.Color(204, 204, 204));
        addStudentBtn.setText("Add Student");
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 280, 50));

        editStudentBtn.setBackground(new java.awt.Color(51, 51, 51));
        editStudentBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        editStudentBtn.setForeground(new java.awt.Color(204, 204, 204));
        editStudentBtn.setText("Edit Student");
        editStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStudentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editStudentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 280, 50));

        backBtn.setBackground(new java.awt.Color(51, 51, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        backBtn.setForeground(new java.awt.Color(204, 204, 204));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDeleteBtnActionPerformed
        SandDStudent searchdeleteStudent = new SandDStudent();
        searchdeleteStudent.setVisible(true);
        dispose();
    }//GEN-LAST:event_searchDeleteBtnActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        AddStudent studentAdd = new AddStudent();
        studentAdd.setVisible(true);
        dispose();
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void editStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStudentBtnActionPerformed
        EditStudent studentEdit = new EditStudent();
        studentEdit.setVisible(true);
        dispose();
    }//GEN-LAST:event_editStudentBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton editStudentBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton searchDeleteBtn;
    // End of variables declaration//GEN-END:variables
}
