/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author ASUS
 */
public class StudentReportModule extends javax.swing.JFrame {

    /**
     * Creates new form StudentReportModule
     */
    public StudentReportModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rollno = new javax.swing.JTextField();
        physics = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        chemistry = new javax.swing.JTextField();
        math = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        generateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(200, 100, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textPane.setBackground(new java.awt.Color(68, 68, 68));
        textPane.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        textPane.setForeground(new java.awt.Color(204, 204, 204));
        textPane.setAlignmentX(2.0F);
        textPane.setAlignmentY(2.0F);
        textPane.setMargin(new java.awt.Insets(8, 9, 8, 9));
        textPane.setMinimumSize(new java.awt.Dimension(66, 26));
        jScrollPane1.setViewportView(textPane);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 380, 550));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Generate Student Report");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Roll Number:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Physics:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Chemistry:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Math:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Marks");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("-----------------------------------------------------------------------");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        rollno.setBackground(new java.awt.Color(51, 51, 51));
        rollno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rollno.setForeground(new java.awt.Color(204, 204, 204));
        rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoActionPerformed(evt);
            }
        });
        getContentPane().add(rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 250, 40));

        physics.setBackground(new java.awt.Color(51, 51, 51));
        physics.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        physics.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(physics, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 250, 40));

        id.setBackground(new java.awt.Color(51, 51, 51));
        id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 250, 40));

        chemistry.setBackground(new java.awt.Color(51, 51, 51));
        chemistry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chemistry.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(chemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 250, 40));

        math.setBackground(new java.awt.Color(51, 51, 51));
        math.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        math.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(math, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 250, 40));

        name.setBackground(new java.awt.Color(51, 51, 51));
        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 250, 40));

        generateBtn.setBackground(new java.awt.Color(51, 51, 51));
        generateBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        generateBtn.setForeground(new java.awt.Color(204, 204, 204));
        generateBtn.setText("Generate");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(generateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, 40));

        backBtn.setBackground(new java.awt.Color(51, 51, 51));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(204, 204, 204));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollnoActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        StudentModule stmodule = new StudentModule();
        stmodule.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
      
        String sid = id.getText();
        String sname = name.getText();
        String rollNum = rollno.getText();
        String phy = physics.getText();
        String che = chemistry.getText();
        String mat = math.getText();
             
        if(sid.matches("^\\d{1,10}$") && sname.matches("^[A-Za-z]+(\\s[A-Za-z]+)*$") && rollNum.matches("^\\d{1,7}$")){
            if(phy.matches("^(100|[1-9][0-9]?|0)$") && che.matches("^(100|[1-9][0-9]?|0)$") && mat.matches("^(100|[1-9][0-9]?|0)$")){
                  try{
           
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection connection = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/sms", "root", "");

                    double phyd = Double.parseDouble(phy);   
                    double chemd = Double.parseDouble(che);
                    double matd = Double.parseDouble(mat);

                    double total = ((phyd + chemd + matd) * 100 ) / 300;

                    String grade = "";
                    
                    if(phyd < 40 || chemd < 40 || matd < 40){
                        grade = "fail";
                    }

                    if(total >= 80){
                        grade = "A";
                    }else if(total >= 60 && total < 80){
                        grade = "B";
                    }else if(total >= 50 && total < 60){
                        grade = "C";
                    }else if(total >= 40 && total < 50){
                        grade = "D";
                    }

                    String query = "insert into reportcards values (?,?,?,?,?,?,?)";
                    PreparedStatement pst = connection.prepareStatement(query);

                    pst.setInt(1, Integer.parseInt(id.getText()));
                    pst.setString(2, name.getText());
                    pst.setInt(3,Integer.parseInt(rollNum));
                    pst.setInt(4, Integer.parseInt(phy));
                    pst.setInt(5,Integer.parseInt(che));
                    pst.setInt(6, Integer.parseInt(mat));
                    pst.setString(7, grade);

                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Data has been saved");
                    textPane.setText("--------------REPORT CARD-------------\n\nStudent Name: "+ sname + "\nRoll Number: "+ rollNum+ "\n\n -----Marks-----\n\nPhysics: " + phy + "\nChmistry: "+ che + "\nMath: "+ mat + "\nGrade: "+ grade);

                    id.setText("");
                    name.setText("");
                    rollno.setText("");
                    physics.setText("");
                    chemistry.setText("");
                    math.setText("");

                    connection.close(); 
            
                 }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(null, e);
                 }
            }else{
                JOptionPane.showMessageDialog(null, "Marks should be 0 to 100 range!");
                
            }
          
     }else{
            JOptionPane.showMessageDialog(null, "Fill personal data correctly.");
            
      }
        
      
    }//GEN-LAST:event_generateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReportModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReportModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField chemistry;
    private javax.swing.JButton generateBtn;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField math;
    private javax.swing.JTextField name;
    private javax.swing.JTextField physics;
    private javax.swing.JTextField rollno;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
