/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolmanagementsystem;

/**
 *
 * @author ASUS
 */
public class TeacherModule extends javax.swing.JFrame {

    /**
     * Creates new form TeacherModule
     */
    public TeacherModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        updateTeacherBtn = new javax.swing.JButton();
        deleteTeacherBtn = new javax.swing.JButton();
        addTeacherBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(320, 120, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TEACHER MODULE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 360, 50));

        backbtn.setBackground(new java.awt.Color(51, 51, 51));
        backbtn.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        backbtn.setForeground(new java.awt.Color(204, 204, 204));
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, 30));

        updateTeacherBtn.setBackground(new java.awt.Color(51, 51, 51));
        updateTeacherBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        updateTeacherBtn.setForeground(new java.awt.Color(204, 204, 204));
        updateTeacherBtn.setText("Edit Teacher ");
        updateTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeacherBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateTeacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 300, 50));

        deleteTeacherBtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteTeacherBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        deleteTeacherBtn.setForeground(new java.awt.Color(204, 204, 204));
        deleteTeacherBtn.setText("Search & Delete Reords");
        deleteTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeacherBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteTeacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 300, 50));

        addTeacherBtn.setBackground(new java.awt.Color(51, 51, 51));
        addTeacherBtn.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        addTeacherBtn.setForeground(new java.awt.Color(204, 204, 204));
        addTeacherBtn.setText("Add Teacher");
        addTeacherBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addTeacherBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 300, 50));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void deleteTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeacherBtnActionPerformed
        DeleteTeacher teacherDelete = new DeleteTeacher();
        teacherDelete.setVisible(true);
        dispose();
    }//GEN-LAST:event_deleteTeacherBtnActionPerformed

    private void addTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherBtnActionPerformed
        AddTeacher teacherAdd = new AddTeacher();
        teacherAdd.setVisible(true);
        dispose();
    }//GEN-LAST:event_addTeacherBtnActionPerformed

    private void updateTeacherBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeacherBtnActionPerformed
        EditTeacher teacherEdit = new EditTeacher();
        teacherEdit.setVisible(true);
        dispose();
    }//GEN-LAST:event_updateTeacherBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTeacherBtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton deleteTeacherBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updateTeacherBtn;
    // End of variables declaration//GEN-END:variables
}
